/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddedToEmbyButton: typeof import('./src/components/AddedToEmbyButton/index.vue')['default']
    BtsowButton: typeof import('./src/components/BtsowButton/index.vue')['default']
    Duplicates_model: typeof import('./src/components/EmbyFolder/components/duplicates_model.vue')['default']
    EmbyButton: typeof import('./src/components/EmbyButton/index.vue')['default']
    EmbyFolder: typeof import('./src/components/EmbyFolder/index.vue')['default']
    EmbyStoreHouse: typeof import('./src/components/EmbyStoreHouse/index.vue')['default']
    OnlinePlay: typeof import('./src/components/OnlinePlay/index.vue')['default']
    Personality: typeof import('./src/components/Personality/index.vue')['default']
    Personality_button: typeof import('./src/components/Personality/personality_button/index.vue')['default']
    Personality_button_eight: typeof import('./src/components/Personality/personality_button/personality_button_eight.vue')['default']
    Personality_button_eleven: typeof import('./src/components/Personality/personality_button/personality_button_eleven.vue')['default']
    Personality_button_fifteen: typeof import('./src/components/Personality/personality_button/personality_button_fifteen.vue')['default']
    Personality_button_five: typeof import('./src/components/Personality/personality_button/personality_button_five.vue')['default']
    Personality_button_four: typeof import('./src/components/Personality/personality_button/personality_button_four.vue')['default']
    Personality_button_fourteen: typeof import('./src/components/Personality/personality_button/personality_button_fourteen.vue')['default']
    Personality_button_loading: typeof import('./src/components/Personality/personality_button_loading/index.vue')['default']
    Personality_button_loading_one: typeof import('./src/components/Personality/personality_button_loading/personality_button_loading_one.vue')['default']
    Personality_button_loading_two: typeof import('./src/components/Personality/personality_button_loading/personality_button_loading_two.vue')['default']
    Personality_button_nine: typeof import('./src/components/Personality/personality_button/personality_button_nine.vue')['default']
    Personality_button_one: typeof import('./src/components/Personality/personality_button/personality_button_one.vue')['default']
    Personality_button_seven: typeof import('./src/components/Personality/personality_button/personality_button_seven.vue')['default']
    Personality_button_six: typeof import('./src/components/Personality/personality_button/personality_button_six.vue')['default']
    Personality_button_ten: typeof import('./src/components/Personality/personality_button/personality_button_ten.vue')['default']
    Personality_button_thirteen: typeof import('./src/components/Personality/personality_button/personality_button_thirteen.vue')['default']
    Personality_button_three: typeof import('./src/components/Personality/personality_button/personality_button_three.vue')['default']
    Personality_button_twelve: typeof import('./src/components/Personality/personality_button/personality_button_twelve.vue')['default']
    Personality_button_two: typeof import('./src/components/Personality/personality_button/personality_button_two.vue')['default']
    Personality_checkbox: typeof import('./src/components/Personality/personality_checkbox/index.vue')['default']
    Personality_checkbox_one: typeof import('./src/components/Personality/personality_checkbox/personality_checkbox_one.vue')['default']
    Personality_tooltips: typeof import('./src/components/Personality/personality_tooltips/index.vue')['default']
    Personality_tooltips_one: typeof import('./src/components/Personality/personality_tooltips/personality_tooltips_one.vue')['default']
    Setting: typeof import('./src/components/OnlinePlay/setting.vue')['default']
    Site_btn: typeof import('./src/components/OnlinePlay/site_btn.vue')['default']
    SiteBtn: typeof import('./src/components/OnlinePlay/siteBtn.vue')['default']
    Tooltips: typeof import('./src/components/Personality/personality_tooltips/tooltips/index.vue')['default']
    TorrentList: typeof import('./src/components/TorrentList/index.vue')['default']
    UpdateChineseButton: typeof import('./src/components/UpdateChineseButton/index.vue')['default']
  }
}
